// priority: 0


onEvent('item.registry', event => {
	event.create('difficulty_changer')
		.displayName("§6难度切换器")
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip1'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip2'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip3'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip4'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip5'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip6'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip7'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip8'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip9'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip10'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip11'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip12'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip13'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip14'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip15'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip16'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip17'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip18'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip19'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip20'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip21'))
		.tooltip(Text.translate('item.kubejs.difficulty_changer.tooltip22'))
		.rarity(Rarity.EPIC),
		event.create('shenqi_shard')
			.displayName("§6神器碎片")
			.tooltip(Text.translate('item.kubejs.shenqi_shard.tooltip'))
			.rarity(Rarity.EPIC),


		event.create('shenqi_ingot')
			.displayName("§6神器零件")
			.tooltip(Text.translate('item.kubejs.shenqi_ingot.tooltip'))
			.rarity(Rarity.EPIC)
	event.create('red_packet')
		.tooltip(Text.translate('item.kubejs.red_packet.tooltip'))
		.rarity(Rarity.EPIC)
	event.create('firecracker')
		.tooltip(Text.translate('item.kubejs.firecracker.tooltip'))
		.rarity(Rarity.EPIC)
	event.create('chinese_dumpling')
		.tooltip(Text.translate('item.kubejs.chinese_dumpling.tooltip'))
		.food((food) => { food.hunger(2).saturation(0.5) })
		.rarity(Rarity.EPIC)
})